### ISSUE TITLE
Can't update submodule overleaf

### ISSUE THREAD

**Issue by Zikoat** [Zikoat/musweeper#2]
Overleaf folder is empty.
I cant init the submodule
I cant update the submodule
I am not added to the overleaf project
@2xic u fix?

**Comment by 2xic** [comment]
> Overleaf folder is empty.

Yeah, that's because of the way overleaf designed things with git. So after you have cloned the repo you have to run 
`git submodule update --init --recursive` for it to fetch the overleaf submodule. 

Maybe if you try to link the project from your overleaf it will also show the overleaf code on github. To do this open the project in overleaf -> menu -> github. 

> I am not added to the overleaf project

Sent you a invite now. So you should be able to run `git submodule update --init --recursive` to get the overleaf code.
